defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 95c9c341-ae02-4982-88fe-7bcd6eeed103 # Home
handle: homePage
maxAuthors: 1
minAuthors: 1
name: 'Home Page'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6e103d22-79eb-4df8-ab84-3faf315eeeab: # Golden Haze
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
